traversable/schema

- .changeset/ripe-buses-look.md
This PR represents the MVP and first release of `@traversable/schema`. Examples and docs to come.
**Checklist** —
> 📦 `@traversable/schema` v0.0.1

- .changeset/large-ways-love.md
- package.json
- packages/schema/package.json
- pnpm-lock.yaml
> fix(schema): promotes @traversable/schema peerDeps to proper depend

- .changeset/eighty-pans-try.md
- packages/schema/package.json
- pnpm-lock.yaml
> fix(schema): adds fast-check to peerDeps

- .changeset/smart-cougars-ring.md
- packages/schema/package.json
- packages/schema/src/__generated__/__manifest__.ts
- packages/schema/src/core.ts
- packages/schema/src/equals.ts
- packages/schema/src/exports.ts
- packages/schema/src/namespace.ts
- packages/schema/src/schema.ts
- packages/schema/test/fast-check.ts
- packages/schema/test/integration.test.ts
- packages/schema/test/schema.test.ts
- packages/schema/test/seed.ts
- packages/schema/test/toString.test.ts
- pnpm-lock.yaml
> feat(schema): reduces bundle footprint by externalizing `Seed` module, `fast-check` dep

- .changeset/itchy-cycles-dance.md
- package.json
- packages/schema/src/combinators.ts
- packages/schema/src/namespace.ts
- packages/schema/src/schema.ts
- packages/schema/test/inline.test.ts
- packages/schema/test/toString.test.ts
- pnpm-lock.yaml
- vite.config.ts
> feat(schema): adds (back) support for inline type predicates

- .changeset/cuddly-cities-burn.md
- .changeset/old-maps-ring.md
- package.json
- packages/registry/src/has.ts
- packages/schema/src/combinators.ts
- packages/schema/src/core.ts
- packages/schema/src/exports.ts
- packages/schema/src/jsonSchema.ts
- packages/schema/src/namespace.ts
- packages/schema/src/predicates.ts
- packages/schema/src/recursive.ts
- packages/schema/src/schema.ts
- packages/schema/src/toString.ts
- packages/schema/test/integration.test.ts
- packages/schema/test/jsonSchema.test.ts
- packages/schema/test/schema.test.ts
- packages/schema/test/seed.ts
- packages/schema/test/toString.test.ts
- pnpm-lock.yaml
- vite.config.ts
> feat(schema): inlines JSON schema types for better "pretty printing"

- packages/schema-zod-adapter/src/__generated__/__manifest__.ts
- packages/schema/src/core.ts
- packages/schema/src/predicates.ts
> perf(schema): precomputes predicate logic ahead of time where possible

- .changeset/violet-foxes-cry.md
- packages/schema/src/combinators.ts
- packages/schema/src/enum.ts
- packages/schema/src/jsonSchema.ts
- packages/schema/src/namespace.ts
- packages/schema/test/combinators.test.ts
- packages/schema/test/integration.test.ts
- packages/schema/test/jsonSchema.test.ts
- packages/schema/test/seed.ts
- packages/schema/test/toString.test.ts
> perf(schema): calls to `jsonSchema` are now lazy

- .changeset/petite-bikes-share.md
- bin/pack.ts
- bin/schema.ts
- packages/schema-to-string/package.json
- packages/schema-to-string/src/__generated__/__manifest__.ts
> build(root): support sideEffects field in package.json

- .changeset/short-frogs-arrive.md
- packages/schema-to-json-schema/package.json
- packages/schema-to-json-schema/src/__generated__/__manifest__.ts
> chore(schema-to-json-schema): adds side effects to package.json

- .changeset/seven-dodos-trade.md
- packages/schema-to-string/test/zod-side-by-side.test.ts
> docs(schema-to-string): cleans up zod side-by-side

- .changeset/fast-teams-join.md
- examples/sandbox/package.json
- examples/sandbox/tsconfig.app.json
- examples/sandbox/tsconfig.node.json
- examples/sandbox/vite.config.ts
- packages/schema-to-json-schema/src/jsonSchema.ts
- packages/schema/src/schema.ts
- pnpm-lock.yaml
> fix(build): fixes sandbox

- .changeset/tall-plants-rhyme.md
- README.md
- packages/derive-validators/src/bind.ts
- packages/derive-validators/src/errors.ts
- packages/derive-validators/test/bind.test.ts
- packages/derive-validators/test/validators.test.ts
> docs(validators): adds docs for `.validate`

- .changeset/four-walls-prove.md
- README.md
> docs: add inferred type predicates example to readme

- bin/workspace.ts
> fix(build): include import attributes in generated workspace file

- examples/sandbox/package.json
- package.json
- pnpm-lock.yaml
> deps(root): upgrades @vitest/coverage-v8 to v3.0.9

- README.md
> docs(root): fixes playground links in README

- .changeset/sour-bees-flow.md
- README.md
- packages/schema/README.md
> docs(schema): adds docs for `@traversable/schema` package

- .changeset/tidy-geckos-yell.md
- packages/registry/src/exports.ts
- packages/schema/src/exports.ts
- packages/schema/src/predicates.ts
- packages/schema/src/utils.ts
- packages/schema/test/bounded.test.ts
- packages/schema/test/has.test.ts
- packages/schema/test/predicates.test.ts
- packages/schema/test/recursive.test.ts
- packages/schema/test/schema.test.ts
> fix(schema,registry): revert back to ES2020-compatible exports

- README.md
> docs(root): adds demo to readme

- .changeset/polite-impalas-smile.md
- packages/zod/README.md
> docs(zod): updates readme with examples, bolt sandbox

- .changeset/ten-cows-boil.md
- README.md
- packages/zod-test/package.json
- packages/zod-test/src/__generated__/__manifest__.ts
- pnpm-lock.yaml
> fix(zod-test): removes unnecessary dependency on `@traversable/json`

- .changeset/large-plants-see.md
- packages/typebox/src/deep-clone.ts
- packages/zod-test/src/generator-seed.ts
- packages/zod-types/src/utils.ts
- packages/zod/README.md
- packages/zod/src/check.ts
- packages/zod/src/deep-clone.ts
- packages/zod/src/exports.ts
- packages/zod/src/to-type.ts
- packages/zod/test/deep-clone.fuzz.test.ts
- packages/zod/test/deep-clone.test.ts
> optimize(zod): makes `zx.deepClone` simpler & ~5x faster

- .changeset/all-carrots-thank.md
- README.md
- bin/bump.ts
- bin/docs.ts
- packages/arktype-test/README.md
- packages/arktype-types/README.md
- packages/arktype/README.md
- packages/json-schema-test/README.md
- packages/json-schema-types/README.md
- packages/json-schema/README.md
- packages/json/README.md
- packages/registry/README.md
- packages/schema-codec/README.md
- packages/schema-compiler/README.md
- packages/schema-deep-equal/README.md
- packages/schema-errors/README.md
- packages/schema-seed/README.md
- packages/schema-to-json-schema/README.md
- packages/schema-to-string/README.md
- packages/schema-to-validator/README.md
- packages/schema-valibot-adapter/README.md
- packages/schema/README.md
- packages/typebox-test/README.md
- packages/typebox-types/README.md
- packages/typebox/README.md
- packages/zod-test/README.md
- packages/zod-types/README.md
- packages/zod/README.md
> docs: removes MIT license from package READMEs

- .changeset/slow-hats-matter.md
- packages/zod/src/deep-clone.ts
- packages/zod/src/deep-equal.ts
> feat(zod): adds `zx.deepClone` support for `z.custom`, `z.success`

- .changeset/sad-papayas-end.md
- packages/valibot-types/src/functor.ts
- packages/valibot-types/src/utils.ts
- packages/valibot/src/deep-equal.ts
- packages/valibot/src/exports.ts
- packages/valibot/test/deep-equal.fuzz.test.ts
- packages/valibot/test/deep-equal.test.ts
> feat(valibot): adds `vx.deepEqual`

- .changeset/afraid-cows-rule.md
- .changeset/cool-windows-divide.md
- .changeset/poor-worms-own.md
- packages/arktype-test/src/generator-seed.ts
- packages/arktype-test/src/generator.ts
- packages/arktype-test/src/typename.ts
- packages/arktype/src/deep-clone.ts
- packages/arktype/test/deep-clone.fuzz.test.ts
- packages/arktype/test/deep-clone.test.ts
- packages/arktype/test/deep-equal.test.ts
- packages/json-schema-types/src/types.ts
- packages/json-schema/src/deep-clone.ts
- packages/json-schema/test/deep-clone.fuzz.test.ts
- packages/json-schema/test/deep-clone.test.ts
- packages/json-schema/test/deep-equal.test.ts
- packages/typebox/src/deep-clone.ts
- packages/typebox/test/deep-clone.fuzz.test.ts
- packages/valibot/src/deep-clone.ts
- packages/valibot/test/deep-clone.fuzz.test.ts
- packages/zod/src/deep-clone.ts
- packages/zod/test/deep-clone.fuzz.test.ts
- packages/zod/test/deep-clone.test.ts
> feat(zod): adds `zx.deepClone` support for `z.object(...).catchall`

- .changeset/spicy-boats-kick.md
- packages/zod-types/src/functor.ts
- packages/zod/test/deep-partial.test.ts
> fix(zod): fixes bug with `zx.deepPartial` unions not preserving schema methods

- .changeset/clever-boxes-relax.md
- packages/zod/src/deep-partial.ts
- packages/zod/test/deep-partial.test.ts
> fix(zod): adds `zx.deepPartial` support for transform schemas

- .changeset/fluffy-cities-tap.md
- .changeset/violet-parks-sleep.md
- packages/zod-types/src/functor.ts
- packages/zod/README.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
> docs(zod): adds better example for `zx.fold`

- .changeset/little-waves-ask.md
- packages/zod-types/src/functor.ts
- packages/zod/src/deep-nullable.ts
- packages/zod/src/deep-optional.ts
- packages/zod/src/deep-partial.ts
- packages/zod/test/deep-partial.test.ts
> fix(zod): fixes `zx.deepPartial` handing of `z.discriminatedUnion`

- .changeset/tired-cups-yell.md
- packages/valibot/src/default-value.ts
- packages/zod/src/default-value.ts
- packages/zod/src/makeLens.ts
- packages/zod/test/default-value.test.ts
> fix(zod): fixes return type for `zx.defaultValue`

- .changeset/soft-pianos-glow.md
- bin/pack.ts
- bin/schema.ts
> chore(*): adds licences to built manifests

- .changeset/large-wolves-lay.md
- packages/zod-types/src/utils.ts
- packages/zod/src/to-string.ts
- packages/zod/test/to-string.test.ts
> fix(zod,zod-types): fixes `zx.toString` bug with `z.default` objects containing an unmatched bracket

- .changeset/mean-cats-float.md
- .changeset/tricky-eagles-fix.md
- packages/zod-test/README.md
- packages/zod-test/package.json
- packages/zod-test/src/__generated__/__manifest__.ts
- packages/zod-test/src/exports.ts
- packages/zod-test/src/fuzz.ts
- packages/zod-test/src/generator-bounds.ts
- packages/zod-test/src/generator.ts
- packages/zod-test/test/fuzz.fuzz.test.ts
- packages/zod-test/test/fuzz.test.ts
- packages/zod-test/test/generator.fuzz.test.ts
- packages/zod-test/test/generator.test.ts
- packages/zod-test/tsconfig.build.json
- packages/zod-test/tsconfig.src.json
- packages/zod-test/tsconfig.test.json
- packages/zod-types/src/functor.ts
- packages/zod/src/to-paths.ts
- packages/zod/src/to-string.ts
- packages/zod/src/to-type.ts
- pnpm-lock.yaml
> feat(zod-test): adds `zxTest.fuzz` for  converting a Zod schemas into fast-check arbitraries

- .changeset/late-houses-drop.md
> chore: adds changelog for #551 fix
